# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ccc3b0c80044b93ca13c025e2afcb03eabb6a5d30424b4500c4ff62ea33945fa94532fbd93c661b9461153078c19311943698a08dddd17f165347129ef01977

test:
  secret_key_base: 61a00e195f77401478d04cd7df65e127bfc6ba6590ae671fb78f55718c0adfa023af969de830b534e6bfa6f586fbc3196347fb061f6ece54590a9aab1aebbafa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
