source 'https://rubygems.org'

gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development

#gem 'simple_token_authentication', '~> 1.0' # see semver.org
gem 'devise'

# Use SCSS for stylesheets
gem 'bootstrap-sass', '~> 3.1.1'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

group :development, :test do 
  gem 'mysql2'
  gem 'byebug'
  gem 'rspec-rails', '~> 3.1.0'
  gem "factory_girl_rails", "~> 4.0"
end

group :production do
  gem 'pg'
end

gem 'compass'